<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>NoDoubleTapSprint</RootNamespace>
		<AssemblyName>NoDoubleTapSprint</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<TargetFramework>net9.0</TargetFramework>
		<FileAlignment>512</FileAlignment>
		<LangVersion>10.0</LangVersion>
		<Nullable>enable</Nullable>
		<Deterministic>true</Deterministic>
		<!-- Change CopyToMods to true if you'd like builds to be moved into the Mods folder automatically-->
		<CopyToMods Condition="'$(CopyToMods)'==''">false</CopyToMods>
		<DebugType Condition="'$(Configuration)'=='Debug'">embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(ResonitePath)'==''">
		<!-- If you don't want to provide a ResonitePath in dotnet build, you can specify one here -->
		<ResonitePath>$(MSBuildThisFileDirectory)Resonite/</ResonitePath>
		<ResonitePath Condition="Exists('C:\Program Files (x86)\Steam\steamapps\common\Resonite\')">C:\Program Files (x86)\Steam\steamapps\common\Resonite\</ResonitePath>
    <ResonitePath Condition="Exists('$(HOME)/.steam/steam/steamapps/common/Resonite/')">$(HOME)/.steam/steam/steamapps/common/Resonite/</ResonitePath>
    <ResonitePath Condition="Exists('P:\SteamLibrary\steamapps\common\Resonite\')">P:\SteamLibrary\steamapps\common\Resonite\</ResonitePath>
	</PropertyGroup>

	<ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" />
    <Reference Include="0Harmony">
      <HintPath>$(ResonitePath)rml_libs\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Renderite.Shared" Publicize="true">
      <HintPath>$(ResonitePath)Renderite.Shared.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FrooxEngine" Publicize="true">
      <HintPath>$(ResonitePath)FrooxEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ResoniteModLoader">
      <HintPath>$(ResonitePath)Libraries\ResoniteModLoader.dll</HintPath>
    </Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(CopyToMods)'=='true'">
    <Message Text="Attempting to copy $(TargetFileName) to $(ResonitePath)rml_mods" Importance="high" />
    <Copy SourceFiles="$(TargetDir)$(TargetFileName)" DestinationFolder="$(ResonitePath)rml_mods" ContinueOnError="true" />
	</Target>
</Project>